build:
  stage: build
  script:
    - echo "Build stage"
    - ./gradlew clean build

test:
  needs: ["build"]
  stage: test
  script: echo "Test stage"

deploy:
  needs: ["test"]
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
