
build:
  stage: build
  script: echo "Build stage"

test:
  stage: test
  script: echo "Test stage"

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
